Git browse function cleanup

diff --git a/git/commands/git-browse b/git/commands/git-browse
--- a/git/commands/git-browse
+++ b/git/commands/git-browse
@@ -3,30 +3,47 @@
 
 # Open a Git remote in the browser
 
-local tool=
+function open_tool {
+    if command -v xdg-open > /dev/null 2>&1; then
+        echo 'xdg-open'
+    elif command -v open > /dev/null 2>&1; then
+        echo 'open'
+    else
+        echo ''
+    fi
+}
 
-if command -v xdg-open > /dev/null 2>&1; then
-    tool='xdg-open'
-elif command -v open > /dev/null 2>&1; then
-    tool='open'
-else
-    echo "fatal: you must have either 'open' or 'xdg-open' installed"
-    return 1
-fi
+function parsed_remote {
+    local remote_info=$(git remote -v | grep -E "^$1\s.*\(fetch\)$")
+    local url=$(echo "$remote_info" | awk '{print $2}' | sed -E 's/.git$//')
 
-local remote_name="${1:-origin}"
-local remote_info=$(git remote -v | grep -E "^$remote_name\s.*\(fetch\)$")
-local remote_url=$(echo "$remote_info" | awk '{print $2}' | sed -E 's/.git$//')
+    echo "$url" | \
+        sed -E 's#^git@#https://#' | \
+        sed -E 's#^(https://.*):(.*)#\1/\2#'
+}
 
-if [[ -z "$remote_url" ]]; then
-    echo "fatal: no remote with name '${remote_name}' was found"
-    return 1
-fi
 
-remote_url=$(echo "$remote_url" | \
-             sed -E 's#^git@#https://#' | \
-             sed -E 's#^(https://.*):(.*)#\1/\2#')
+function browse {
+    if [[ -z "$1" ]]; then
+        echo -e "warning: no remote name given. Using origin as default\n"
+    fi
 
-eval "$tool $remote_url"
+    local remote="${1:-origin}"
+    local tool="$(open_tool)"
+    local url="$(parsed_remote $remote)"
 
-unset remote_info remote_name remote_url tool
+    if [[ -z "$tool" ]]; then
+        echo "fatal: you must have either 'open' or 'xdg-open' installed"
+        return 1
+    fi
+
+    if [[ -z "$url" ]]; then
+        echo "fatal: no remote with name '$remote' was found"
+        return 1
+    fi
+
+    echo "Browsing to $url..."
+    eval "$tool $url" 2> /dev/null || echo "fatal: cannot browse to $url"
+}
+
+browse "$@"
